import type { ApiDocItem } from "./types";

export const REQUEST_RESPONSE_DOCS: ApiDocItem[] = [
	{
		id: "api-input",
		name: "input",
		kind: "property",
		signature: "const input: any;",
		description: "Output from preceding block in execution DAG.",
		category: "request",
		example: "const data = input;\nreturn data;",
		returns: "any",
	},
	{
		id: "api-httpRequestMethod",
		name: "httpRequestMethod",
		kind: "property",
		signature: "const httpRequestMethod: string;",
		description: 'Incoming HTTP method, e.g. "GET", "POST", "PUT", "DELETE".',
		category: "request",
		example: 'if (httpRequestMethod === "POST") {\n  // handle POST\n}',
		returns: "string",
	},
	{
		id: "api-httpRequestRoute",
		name: "httpRequestRoute",
		kind: "property",
		signature: "const httpRequestRoute: string;",
		description: 'Incoming request path/route, e.g. "/api/v1/users".',
		category: "request",
		example: "logger.logInfo({ path: httpRequestRoute });",
		returns: "string",
	},
	{
		id: "api-getQueryParam",
		name: "getQueryParam",
		kind: "function",
		signature: "getQueryParam(key: string): string",
		description: 'Reads incoming query parameter by key, or returns "" if absent.',
		category: "params",
		example: 'const page = Number(getQueryParam("page") || "1");',
		returns: "string",
	},
	{
		id: "api-getRouteParam",
		name: "getRouteParam",
		kind: "function",
		signature: "getRouteParam(key: string): string",
		description: 'Reads incoming named route parameter, or returns "" if absent.',
		category: "params",
		example: 'const id = getRouteParam("id");\nif (!id) throw new Error("Missing ID");',
		returns: "string",
	},
	{
		id: "api-getHeader",
		name: "getHeader",
		kind: "function",
		signature: "getHeader(key: string): string",
		description: 'Reads case-insensitive request header, or returns "" if absent.',
		category: "request",
		example: 'const auth = getHeader("authorization");',
		returns: "string",
	},
	{
		id: "api-getCookie",
		name: "getCookie",
		kind: "function",
		signature: "getCookie(key: string): string",
		description: 'Reads request cookie value by name, or returns "" if absent.',
		category: "request",
		example: 'const sessionId = getCookie("sessionId");',
		returns: "string",
	},
	{
		id: "api-getRequestBody",
		name: "getRequestBody",
		kind: "function",
		signature: "getRequestBody(): any",
		description: "Returns parsed incoming request body payload.",
		category: "request",
		example: "const body = getRequestBody();",
		returns: "any",
	},
	{
		id: "api-setHeader",
		name: "setHeader",
		kind: "function",
		signature: "setHeader(key: string, value: string): void",
		description: "Sets an outgoing response header.",
		category: "response",
		example: 'setHeader("Cache-Control", "no-store, no-cache");',
		returns: "void",
	},
	{
		id: "api-setCookie",
		name: "setCookie",
		kind: "function",
		signature: "setCookie(name: string, options: CookieOptions): void",
		description: "Sets an outgoing cookie with expiry, httpOnly, secure, and samesite.",
		category: "response",
		example:
			'setCookie("session", {\n  value: "xyz",\n  httpOnly: true,\n  secure: true,\n  samesite: "Strict",\n});',
		returns: "void",
	},
	{
		id: "api-getConfig",
		name: "getConfig",
		kind: "function",
		signature: "getConfig(key: string): string | number | boolean | undefined",
		description: "Retrieves project App Config value, or undefined if not set.",
		category: "config",
		example: 'const secret = getConfig("JWT_SECRET");',
		returns: "string | number | boolean | undefined",
	},
	{
		id: "api-global-variables",
		name: "[globalVariable]",
		kind: "property",
		signature: "myVar = value; // read via bare identifier: myVar",
		description:
			"Variables set in blocks or scripts are available globally in scope across later blocks in the same request.",
		category: "variables",
		example: "currentUserId = input.id;\nconst id = currentUserId;",
		returns: "any",
	},
];
