apiVersion: v1
kind: ConfigMap
metadata:
  name: fluxify-config
  namespace: {{ .Release.Namespace }}
  labels: {{- include "fluxify.labels" . | nindent 4 }}
data: {{- include "fluxify.config" . | nindent 2 }}
