/**
 * In-memory codec benchmark. No broker, no sockets — encode and decode only,
 * so the numbers are the codec and nothing else.
 *
 *   bun packages/common/nats/bench/codec.bench.ts
 *   bun packages/common/nats/bench/codec.bench.ts --iterations 5000
 *
 * Why this exists: `codec.ts` carries a doc comment claiming msgpack wins on
 * size and loses on CPU. That claim decides whether a subject opts in, so it
 * should be reproducible rather than remembered from one afternoon.
 *
 * The datasets are the real payload shapes on the bus, not synthetic filler —
 * a job envelope, a compile request, a trace run, a canvas apply, a batch, and
 * the two adversarial cases (raw bytes, incompressible noise) where the
 * defaults are known to behave badly.
 */
import {
	gzipJsonCodec,
	gzipMsgpackCodec,
	jsonCodec,
	msgpackCodec,
	type Codec,
} from "../codec";

const argIterations = Number(
	process.argv[process.argv.indexOf("--iterations") + 1],
);
const SCALE =
	Number.isFinite(argIterations) && argIterations > 0 ? argIterations : 0;

interface Dataset {
	name: string;
	value: unknown;
	/**
	 * What the JSON codecs are given instead, when `value` holds something JSON
	 * cannot represent. Comparing msgpack's raw bytes against a JSON object that
	 * silently lost them is not a comparison.
	 */
	jsonValue?: unknown;
	iterations: number;
	note?: string;
}

/** Deterministic, so two runs on one machine are comparable. */
function rng(seed: number) {
	let state = seed >>> 0;
	return () => {
		state = (state * 1_664_525 + 1_013_904_223) >>> 0;
		return state / 0x1_0000_0000;
	};
}

const random = rng(20260829);
const pick = <T>(items: T[]) => items[Math.floor(random() * items.length)]!;
const id = (prefix: string) =>
	`${prefix}_${Math.floor(random() * 0xff_ffff)
		.toString(16)
		.padStart(6, "0")}`;

function jobEnvelope() {
	return {
		id: crypto.randomUUID(),
		projectId: crypto.randomUUID(),
		kind: "custom-block",
		target: id("cb"),
		enqueuedAt: new Date().toISOString(),
		attempt: 1,
		payload: { retries: 0, source: "api" },
	};
}

function traceRun(spanCount: number) {
	const origin = 5_000;
	return {
		runId: crypto.randomUUID(),
		projectId: crypto.randomUUID(),
		routeId: id("route"),
		routeVersion: new Date().toISOString(),
		method: "POST",
		path: "/orders/:orderId/items",
		startedAtWallMs: Date.now(),
		perfOrigin: origin,
		endedAt: origin + spanCount * 4,
		outcome: "success",
		statusCode: 200,
		spans: Array.from({ length: spanCount }, (_, seq) => ({
			seq,
			blockId: id("blk"),
			blockType: pick(["jsrunner", "db", "http", "condition", "response"]),
			startedAt: origin + seq * 4,
			endedAt: origin + seq * 4 + 3,
			outcome: "success",
			input: { index: seq, cursor: null },
			output: { rows: seq % 7, elapsedMs: Number((random() * 10).toFixed(3)) },
		})),
	};
}

/** The RPC bulk case: repetitive keys, long JS strings, deep-ish nesting. */
function canvas(blockCount: number) {
	return {
		blocks: Array.from({ length: blockCount }, (_, i) => ({
			id: `blk_${i}`,
			type: pick(["jsrunner", "db", "http", "condition"]),
			position: { x: (i % 8) * 240, y: Math.floor(i / 8) * 160 },
			data: {
				name: `Step ${i}`,
				description: "Generated by the canvas benchmark fixture.",
				code: "return input.items.map((x) => ({ ...x, seen: true }));",
				conditions: [{ lhs: "vars.status", op: "eq", rhs: "ready" }],
			},
		})),
		edges: Array.from({ length: Math.max(0, blockCount - 1) }, (_, i) => ({
			id: `edge_${i}`,
			from: `blk_${i}`,
			to: `blk_${i + 1}`,
		})),
	};
}

/** The shape the doc comment's numbers came from: many records, same keys. */
function batch(size: number) {
	return Array.from({ length: size }, (_, i) => ({
		id: crypto.randomUUID(),
		sequence: i,
		receivedAt: Date.now() + i,
		partition: i % 12,
		offset: 4_000_000 + i,
		headers: {
			source: "kafka",
			topic: "orders.v2",
			contentType: "application/json",
		},
		body: {
			orderId: id("ord"),
			total: Number((random() * 500).toFixed(2)),
			currency: "USD",
		},
	}));
}

function bytes(length: number, compressible: boolean) {
	const out = new Uint8Array(length);
	if (compressible) {
		// a run-heavy buffer, the way a screenshot or a padded blob looks
		for (let i = 0; i < length; i++) out[i] = (i >> 6) & 0xff;
	} else {
		for (let i = 0; i < length; i++) out[i] = Math.floor(random() * 256);
	}
	return out;
}

const base64 = (data: Uint8Array) => Buffer.from(data).toString("base64");
const COMPRESSIBLE_BLOB = bytes(256 * 1024, true);
const RANDOM_BLOB = bytes(256 * 1024, false);

const DATASETS: Dataset[] = [
	{
		name: "job envelope",
		value: jobEnvelope(),
		iterations: 20_000,
		note: "the common case — small, published constantly",
	},
	{
		name: "compile request",
		value: { id: id("route"), reason: "route changed" },
		iterations: 20_000,
		note: "smallest real payload on the bus",
	},
	{
		name: "trace run (40 spans)",
		value: traceRun(40),
		iterations: 5_000,
		note: "telemetry: number-heavy, repeated keys",
	},
	{
		name: "trace run (400 spans)",
		value: traceRun(400),
		iterations: 500,
		note: "a slow route with a loop in it",
	},
	{
		name: "canvas (50 blocks)",
		value: canvas(50),
		iterations: 2_000,
		note: "RPC: the everyday canvas apply",
	},
	{
		name: "canvas (1000 blocks)",
		value: canvas(1000),
		iterations: 100,
		note: "RPC: near the 1MiB max_payload ceiling as plain JSON",
	},
	{
		name: "batch (500 records)",
		value: batch(500),
		iterations: 500,
		note: "the shape codec.ts quotes its numbers from",
	},
	{
		name: "binary 256KiB (compressible)",
		value: { blobId: "blob_a", data: COMPRESSIBLE_BLOB },
		jsonValue: { blobId: "blob_a", data: base64(COMPRESSIBLE_BLOB) },
		iterations: 200,
		note: "JSON must base64 it; msgpack sends bytes",
	},
	{
		name: "binary 256KiB (random)",
		value: { blobId: "blob_b", data: RANDOM_BLOB },
		jsonValue: { blobId: "blob_b", data: base64(RANDOM_BLOB) },
		iterations: 200,
		note: "incompressible — gzip is pure cost here",
	},
	{
		name: "incompressible strings",
		value: Array.from({ length: 8_000 }, () =>
			Math.floor(random() * 0xffff_ffff).toString(36),
		),
		iterations: 200,
		note: "high entropy: the case where gzip should be refused",
	},
];

const CODECS: Array<{ name: string; codec: Codec<unknown> }> = [
	{ name: "json", codec: jsonCodec() },
	// threshold 0 so the gzip rows always actually gzip; in production the
	// default 32KiB means small payloads stay plain and readable on the wire
	{ name: "json+gzip", codec: gzipJsonCodec(0) },
	{ name: "msgpack", codec: msgpackCodec() },
	{ name: "msgpack+gzip", codec: gzipMsgpackCodec(0) },
];

interface Result {
	codec: string;
	bytes: number;
	encodeMs: number;
	decodeMs: number;
	lossless: boolean;
}

function time(runs: number, fn: () => void): number {
	const started = performance.now();
	for (let i = 0; i < runs; i++) fn();
	return (performance.now() - started) / runs;
}

/**
 * Structural equality that treats a byte array as bytes. `JSON.stringify` turns
 * a Uint8Array into `{"0":…}`, which makes a lossy JSON round trip look correct.
 */
function equal(a: unknown, b: unknown): boolean {
	if (a === b) return true;
	const aBytes = ArrayBuffer.isView(a);
	const bBytes = ArrayBuffer.isView(b);
	if (aBytes || bBytes) {
		if (!aBytes || !bBytes) return false;
		// msgpack decodes a `bin` as a zero-copy subarray of the whole message,
		// so the view's offset and length matter — comparing `.buffer` compares
		// the encoded frame, not the value, and reports a false mismatch.
		const view = (v: ArrayBufferView) =>
			new Uint8Array(v.buffer as ArrayBuffer, v.byteOffset, v.byteLength);
		const x = view(a as ArrayBufferView);
		const y = view(b as ArrayBufferView);
		return x.length === y.length && x.every((v, i) => v === y[i]);
	}
	if (a === null || b === null || typeof a !== "object" || typeof b !== "object")
		return false;
	if (Array.isArray(a) !== Array.isArray(b)) return false;
	const ka = Object.keys(a as object);
	const kb = Object.keys(b as object);
	if (ka.length !== kb.length) return false;
	return ka.every((k) =>
		equal((a as Record<string, unknown>)[k], (b as Record<string, unknown>)[k]),
	);
}

function measure(dataset: Dataset): Result[] {
	const runs = SCALE || dataset.iterations;
	return CODECS.map(({ name, codec }) => {
		const value =
			name.startsWith("json") && dataset.jsonValue !== undefined
				? dataset.jsonValue
				: dataset.value;

		// warm the JIT before measuring, or the first codec pays for the rest
		for (let i = 0; i < Math.min(50, runs); i++)
			codec.decode(codec.encode(value));

		const encoded = codec.encode(value);
		return {
			codec: name,
			bytes: encoded.length,
			encodeMs: time(runs, () => void codec.encode(value)),
			decodeMs: time(runs, () => void codec.decode(encoded)),
			lossless: equal(codec.decode(encoded), value),
		};
	});
}

const kib = (n: number) => `${(n / 1024).toFixed(1)}K`;
const ms = (n: number) => (n < 0.01 ? n.toFixed(4) : n.toFixed(3));
const pad = (s: string, width: number) => s.padEnd(width);
const padLeft = (s: string, width: number) => s.padStart(width);

console.log(
	`\nNATS codec benchmark — bun ${process.versions.bun ?? "?"}, in memory, no broker`,
);
if (SCALE) console.log(`iterations overridden: ${SCALE} per measurement`);

let msgpackSmaller = 0;
let jsonFaster = 0;

for (const dataset of DATASETS) {
	const results = measure(dataset);
	const baseline = results[0]!.bytes;
	const runs = SCALE || dataset.iterations;

	console.log(`\n${dataset.name}${dataset.note ? `  — ${dataset.note}` : ""}`);
	console.log(
		`  ${pad("codec", 14)}${padLeft("size", 9)}${padLeft("vs json", 9)}${padLeft("encode", 11)}${padLeft("decode", 11)}   (n=${runs})`,
	);
	for (const r of results) {
		const ratio =
			r.bytes === baseline ? "—" : `${((r.bytes / baseline) * 100).toFixed(0)}%`;
		const warn = r.lossless ? "" : "   ** LOSSY **";
		console.log(
			`  ${pad(r.codec, 14)}${padLeft(kib(r.bytes), 9)}${padLeft(ratio, 9)}${padLeft(`${ms(r.encodeMs)}ms`, 11)}${padLeft(`${ms(r.decodeMs)}ms`, 11)}${warn}`,
		);
	}

	const json = results.find((r) => r.codec === "json")!;
	const msgpack = results.find((r) => r.codec === "msgpack")!;
	if (msgpack.bytes < json.bytes) msgpackSmaller++;
	if (json.encodeMs + json.decodeMs < msgpack.encodeMs + msgpack.decodeMs)
		jsonFaster++;
}

console.log(`
Reading this:
  size    msgpack wins on records with repeated keys, and wins hugely on raw
          bytes, which JSON has to base64 (+33% before it even starts).
  cpu     JSON wins nearly everywhere. JSON.parse/stringify are native engine
          code; @msgpack/msgpack is a JavaScript loop. No pure-JS codec beats
          that, so this is not a library to shop around for.
  gzip    worth it above ~32KiB of repetitive payload, pure cost on the
          high-entropy rows — which is why gzipJsonCodec takes a threshold
          rather than compressing everything.

msgpack was smaller on ${msgpackSmaller}/${DATASETS.length} datasets; JSON was faster on ${jsonFaster}/${DATASETS.length}.
Bytes matter against the 1MiB max_payload ceiling, stream storage, and cross-AZ
egress. CPU matters on the request path. Pick per subject; the default is JSON.
`);
