#!/bin/sh
set -e

echo "[kit] Starting Fluxify services..."

DATA_DIR="${KIT_DATA_DIR:-/data}"
PGDATA="$DATA_DIR/postgres"
NATS_STORE="$DATA_DIR/nats"
SECRETS_FILE="$DATA_DIR/secrets.env"

# "name:pid name:pid ..." — names are only used to say WHICH service died.
services=""
start() {
	_name="$1"
	shift
	"$@" &
	services="$services $_name:$!"
}

pids_of_services() {
	for entry in $services; do
		printf '%s ' "${entry##*:}"
	done
}

# Forward SIGTERM/SIGINT to every child, then wait for them to drain.
# Without this trap the shell (PID 1 under tini) swallows the signal and the
# backgrounded services are orphaned — `docker stop` hangs until SIGKILL.
shutting_down=0
term() {
	shutting_down=1
	echo "[kit] signal received — stopping services..."
	# shellcheck disable=SC2046
	kill -TERM $(pids_of_services) 2>/dev/null || true
	wait
	exit 0
}
trap term TERM INT

die() {
	echo "[kit] FATAL: $1" >&2
	exit 1
}

# Polls a readiness command until it succeeds. Each service gets its own probe
# rather than a generic port check: busybox `nc` has no portable -z, and an open
# port does not mean postgres is accepting queries anyway.
wait_until() {
	_label="$1"
	shift
	_n=0
	while [ "$_n" -lt 60 ]; do
		if "$@" >/dev/null 2>&1; then
			return 0
		fi
		_n=$((_n + 1))
		sleep 1
	done
	die "$_label did not become ready after 60s"
}

# ------------------------------------------------------------------------------
# Secrets — generated once on first boot and reused from the data volume.
#
# Without this a bare `docker run` fails: MASTER_ENCRYPTION_KEY and
# BETTER_AUTH_SECRET are required and have no safe default. Anything explicitly
# passed in the environment always wins over the generated file.
# ------------------------------------------------------------------------------
provision_secrets() {
	if [ -f "$SECRETS_FILE" ]; then
		# shellcheck disable=SC1090
		. "$SECRETS_FILE"
	fi

	_generated=0
	for var in MASTER_ENCRYPTION_KEY BETTER_AUTH_SECRET SYSTEM_ACCESS_KEY; do
		eval "_current=\$$var"
		if [ -z "$_current" ]; then
			eval "$var=\$(head -c 32 /dev/urandom | base64 | tr -d '\n')"
			_generated=1
		fi
		eval "export $var"
	done

	if [ "$_generated" = "1" ]; then
		umask 077
		{
			echo "# Generated by the Fluxify kit on first boot. Losing this file means"
			echo "# stored project credentials can no longer be decrypted."
			for var in MASTER_ENCRYPTION_KEY BETTER_AUTH_SECRET SYSTEM_ACCESS_KEY; do
				eval "printf '%s=%s\n' \"$var\" \"\$$var\""
			done
		} >"$SECRETS_FILE"
		echo "[kit] generated instance secrets -> $SECRETS_FILE (back this up)"
	fi
}

# ------------------------------------------------------------------------------
# Admin credentials.
#
# The seeder skips silently when these are missing or malformed, which leaves a
# running instance nobody can log into. Refuse to boot a fresh database instead
# — the failure is the same either way, but this one explains itself.
# ------------------------------------------------------------------------------
require_admin_credentials() {
	_why="$1"
	[ -n "$SEED_USER_EMAIL" ] ||
		die "SEED_USER_EMAIL is required ($_why). Without it no admin account is created and the UI cannot be logged into."
	[ -n "$SEED_USER_PASSWORD" ] ||
		die "SEED_USER_PASSWORD is required ($_why). Without it no admin account is created and the UI cannot be logged into."
	case "$SEED_USER_EMAIL" in
	?*@?*.?*) ;;
	*) die "SEED_USER_EMAIL ('$SEED_USER_EMAIL') is not a valid email address; the seeder would reject it and create no admin account." ;;
	esac
	[ "${#SEED_USER_PASSWORD}" -ge 8 ] ||
		die "SEED_USER_PASSWORD must be at least 8 characters; the seeder would reject it and create no admin account."
}

# ------------------------------------------------------------------------------
# Bundled backing services.
#
# Each starts only when its connection variable is absent, so setting PG_URL /
# NATS_URL / REDIS_HOST (as docker-compose.yml does) opts out of the bundled
# copy and points the stack at an external one. Same image either way.
# ------------------------------------------------------------------------------
start_bundled_postgres() {
	_fresh=0
	if [ ! -s "$PGDATA/PG_VERSION" ]; then
		_fresh=1
		# Fresh database => nobody has an account yet. Check before initdb so a
		# misconfigured run fails in a second rather than after a full boot.
		require_admin_credentials "this is a first boot with the bundled database"
		echo "[kit] initialising bundled PostgreSQL in $PGDATA..."
		mkdir -p "$PGDATA"
		chmod 700 "$PGDATA"
		# trust auth is safe here: postgres listens on loopback inside this
		# container only and the port is never published.
		initdb --username=postgres --auth-local=trust --auth-host=trust \
			--encoding=UTF8 --pgdata="$PGDATA" >/dev/null
	fi

	echo "[kit] starting bundled PostgreSQL..."
	start postgres postgres -D "$PGDATA" \
		-c listen_addresses=127.0.0.1 \
		-c port=5432 \
		-c unix_socket_directories="$DATA_DIR"

	wait_until "bundled PostgreSQL" pg_isready -h 127.0.0.1 -p 5432 -U postgres -q

	if [ "$_fresh" = "1" ]; then
		createdb -h 127.0.0.1 -U postgres fluxify
		echo "[kit] created database 'fluxify'"
	fi

	export PG_URL="postgres://postgres@127.0.0.1:5432/fluxify"
}

start_bundled_nats() {
	echo "[kit] starting bundled NATS (JetStream)..."
	mkdir -p "$NATS_STORE"
	# -js is REQUIRED: the compile work queue is a JetStream stream and compiled
	# routes live in a KV bucket, which is built on JetStream.
	# -m enables the monitoring endpoint, which is how we probe readiness.
	if [ -n "$NATS_TOKEN" ]; then
		start nats nats-server -js --store_dir "$NATS_STORE" \
			--addr 127.0.0.1 --port 4222 -m 8222 --auth "$NATS_TOKEN"
	else
		start nats nats-server -js --store_dir "$NATS_STORE" \
			--addr 127.0.0.1 --port 4222 -m 8222
	fi
	wait_until "bundled NATS" wget -qO- http://127.0.0.1:8222/healthz
	export NATS_URL="nats://127.0.0.1:4222"
}

start_bundled_valkey() {
	echo "[kit] starting bundled Valkey..."
	# Cache only — pub/sub moved to NATS — so persistence buys nothing and an
	# unwritable/half-written dump would just be a new failure mode.
	start valkey valkey-server --save '' --appendonly no \
		--bind 127.0.0.1 --port 6379
	wait_until "bundled Valkey" valkey-cli -h 127.0.0.1 -p 6379 ping
	export REDIS_HOST=127.0.0.1
	export REDIS_PORT="${REDIS_PORT:-6379}"
	unset REDIS_USER REDIS_PASS
}

mkdir -p "$DATA_DIR"
provision_secrets

[ -n "$PG_URL" ] || start_bundled_postgres
[ -n "$NATS_URL" ] || start_bundled_nats
[ -n "$REDIS_HOST" ] || start_bundled_valkey

# External database: we cannot tell whether it is already seeded, so warn rather
# than refuse — an existing deployment restarting must not be blocked.
if [ -z "$SEED_USER_EMAIL" ] || [ -z "$SEED_USER_PASSWORD" ]; then
	echo "[kit] WARNING: SEED_USER_EMAIL / SEED_USER_PASSWORD are unset. If this"
	echo "[kit]          database has no admin account yet, nothing can log in."
fi

# Admin/control-plane server. Runs migrations and hosts the compiler, which
# turns saved routes into JavaScript and publishes them to the NATS KV bucket.
start server bun --cwd=/app/server standalone.js

# Everything downstream reads tables the admin server creates, so nothing else
# may start until its migrations have run. The AI gateway has no schema-wait of
# its own and dies outright on a missing app_config.
wait_until "admin server" \
	wget -qO- "http://127.0.0.1:${SERVER_PORT:-5500}/_/admin/api/public-settings"

# Telemetry is admin-plane work: it drains route runs from JetStream and exports
# them using each project's configured destination.
start telemetry bun --cwd=/app/server telemetryWorker.js

# Compiled request worker — serves user API traffic from those artifacts.
#
# It serves exactly one project, so it cannot start before a project exists.
# On a first boot that is the normal state: bring the kit up without it, create
# a project in the UI, then set WORKER_PROJECT_ID and restart.
if [ -n "$WORKER_PROJECT_ID" ]; then
	start worker bun --cwd=/app/server compiledWorker.js
else
	echo "[kit] WORKER_PROJECT_ID is not set — starting without the request worker."
	echo "[kit] Create a project at /_/admin/ui, then set WORKER_PROJECT_ID and restart."
fi

# The admin UI is a static Vite bundle in /app/portal, served by Caddy — there
# is no UI process to start.

# AI Gateway
start ai-gateway bun --cwd=/app/ai-gateway server.js

# Reverse proxy — the single published port
start caddy caddy run --config /app/Caddyfile

echo "[kit] All services launched."

# Supervision: a bare `wait` blocks until EVERY child exits, so one dead service
# leaves the container "up" and quietly broken. Poll instead and exit non-zero
# on the first death — `restart: unless-stopped` then restarts the whole kit.
# ponytail: whole-container restart, not per-service; add a real supervisor
# (s6-overlay) only if partial restarts turn out to matter.
while [ "$shutting_down" = "0" ]; do
	for entry in $services; do
		if ! kill -0 "${entry##*:}" 2>/dev/null; then
			echo "[kit] service '${entry%%:*}' exited — stopping the container" >&2
			kill -TERM $(pids_of_services) 2>/dev/null || true
			exit 1
		fi
	done
	sleep 5
done

wait
