import type { IconType } from "react-icons";
import {
	TbActivity,
	TbAdjustments,
	TbAlertTriangle,
	TbAntenna,
	TbApi,
	TbArchive,
	TbAtom,
	TbBarcode,
	TbBattery,
	TbBell,
	TbBellRinging,
	TbBinary,
	TbBinaryTree,
	TbBluetooth,
	TbBolt,
	TbBook,
	TbBookmark,
	TbBox,
	TbBoxMultiple,
	TbBraces,
	TbBrackets,
	TbBrain,
	TbBrandApple,
	TbBrandAws,
	TbBrandAzure,
	TbBrandBitbucket,
	TbBrandCloudflare,
	TbBrandDebian,
	TbBrandDiscord,
	TbBrandDjango,
	TbBrandDocker,
	TbBrandFacebook,
	TbBrandFigma,
	TbBrandFirebase,
	TbBrandGithub,
	TbBrandGitlab,
	TbBrandGmail,
	TbBrandGolang,
	TbBrandGoogle,
	TbBrandInstagram,
	TbBrandJavascript,
	TbBrandJira,
	TbBrandLaravel,
	TbBrandLinkedin,
	TbBrandMongodb,
	TbBrandMysql,
	TbBrandNextjs,
	TbBrandNodejs,
	TbBrandNotion,
	TbBrandNpm,
	TbBrandOpenai,
	TbBrandPaypal,
	TbBrandPhp,
	TbBrandPython,
	TbBrandReact,
	TbBrandRust,
	TbBrandSlack,
	TbBrandStripe,
	TbBrandSupabase,
	TbBrandTelegram,
	TbBrandTrello,
	TbBrandTypescript,
	TbBrandUbuntu,
	TbBrandVercel,
	TbBrandVue,
	TbBrandWhatsapp,
	TbBrandWindows,
	TbBrandX,
	TbBrandYoutube,
	TbBriefcase,
	TbBroadcast,
	TbBug,
	TbBuildingSkyscraper,
	TbBuildingStore,
	TbCalendar,
	TbCalendarEvent,
	TbCamera,
	TbCertificate,
	TbChartBar,
	TbChartDots,
	TbChartLine,
	TbChartPie,
	TbCheck,
	TbClipboard,
	TbClipboardCheck,
	TbClock,
	TbClockHour4,
	TbCloud,
	TbCloudComputing,
	TbCloudDataConnection,
	TbCloudDownload,
	TbCloudLock,
	TbCloudOff,
	TbCloudUpload,
	TbCode,
	TbCompass,
	TbCopy,
	TbCpu,
	TbCpu2,
	TbCreditCard,
	TbCurrencyDollar,
	TbDatabase,
	TbDatabaseCog,
	TbDatabaseExport,
	TbDatabaseImport,
	TbDatabasePlus,
	TbDatabaseSearch,
	TbDeviceDesktop,
	TbDeviceLaptop,
	TbDeviceMobile,
	TbDeviceTablet,
	TbDeviceWatch,
	TbDownload,
	TbDroplet,
	TbEdit,
	TbEye,
	TbFile,
	TbFileCode,
	TbFileExport,
	TbFileImport,
	TbFileText,
	TbFileZip,
	TbFiles,
	TbFilter,
	TbFingerprint,
	TbFlag,
	TbFlame,
	TbFlask,
	TbFolder,
	TbFolderOpen,
	TbFolderPlus,
	TbGauge,
	TbGift,
	TbGitBranch,
	TbGitCommit,
	TbGitCompare,
	TbGitFork,
	TbGitMerge,
	TbGitPullRequest,
	TbGlobe,
	TbHeadphones,
	TbHeart,
	TbHelp,
	TbHierarchy,
	TbHistory,
	TbHourglass,
	TbId,
	TbInbox,
	TbInfoCircle,
	TbJson,
	TbKey,
	TbKeyboard,
	TbLanguage,
	TbLayersIntersect,
	TbLeaf,
	TbLifebuoy,
	TbLink,
	TbLoader,
	TbLock,
	TbLockOpen,
	TbLogin,
	TbLogout,
	TbMail,
	TbMailForward,
	TbMap2,
	TbMapPin,
	TbMathFunction,
	TbMessage,
	TbMessages,
	TbMicrophone,
	TbMicroscope,
	TbMoodSmile,
	TbMouse,
	TbNetwork,
	TbNotebook,
	TbPackage,
	TbPackageExport,
	TbPackages,
	TbPaperclip,
	TbPhoto,
	TbPin,
	TbPlayerPause,
	TbPlayerPlay,
	TbPlayerStop,
	TbPlug,
	TbPlugConnected,
	TbPrinter,
	TbPuzzle,
	TbQrcode,
	TbRefresh,
	TbRegex,
	TbRepeat,
	TbReportAnalytics,
	TbRobot,
	TbRocket,
	TbRouter,
	TbSatellite,
	TbScan,
	TbSchool,
	TbSearch,
	TbSend,
	TbServer,
	TbServer2,
	TbServerBolt,
	TbServerCog,
	TbSettings,
	TbShare,
	TbShield,
	TbShieldCheck,
	TbShieldLock,
	TbShoppingCart,
	TbSitemap,
	TbSparkles,
	TbSpeakerphone,
	TbSql,
	TbStack2,
	TbStar,
	TbTable,
	TbTableExport,
	TbTag,
	TbTags,
	TbTargetArrow,
	TbTemperature,
	TbTerminal2,
	TbThumbUp,
	TbTicket,
	TbTool,
	TbTools,
	TbTopologyStar,
	TbTrash,
	TbTrendingUp,
	TbTruckDelivery,
	TbUnlink,
	TbUpload,
	TbUsb,
	TbUser,
	TbUserCheck,
	TbUserPlus,
	TbUserShield,
	TbUsers,
	TbVariable,
	TbVideo,
	TbVolume,
	TbWand,
	TbWebhook,
	TbWifi,
	TbWorld,
	TbWorldWww,
	TbX,} from "react-icons/tb";
import type { PremadeIconType } from "@fluxify/server/src/api/v1/custom-blocks/shared";

/**
 * The premade icon set offered in the custom block settings. Typed against the
 * server enum, so adding one here without adding it there (or vice versa) is a
 * typecheck error rather than a runtime "Invalid premade icon name" 400.
 */
export const PREMADE_ICONS: Record<PremadeIconType, IconType> = {
	"code": TbCode,
	"terminal-2": TbTerminal2,
	"bug": TbBug,
	"braces": TbBraces,
	"brackets": TbBrackets,
	"binary": TbBinary,
	"api": TbApi,
	"webhook": TbWebhook,
	"math-function": TbMathFunction,
	"variable": TbVariable,
	"regex": TbRegex,
	"json": TbJson,
	"sql": TbSql,
	"file-code": TbFileCode,
	"git-branch": TbGitBranch,
	"git-commit": TbGitCommit,
	"git-merge": TbGitMerge,
	"git-pull-request": TbGitPullRequest,
	"git-fork": TbGitFork,
	"brand-github": TbBrandGithub,
	"brand-gitlab": TbBrandGitlab,
	"brand-bitbucket": TbBrandBitbucket,
	"package": TbPackage,
	"packages": TbPackages,
	"brand-npm": TbBrandNpm,
	"brand-docker": TbBrandDocker,
	"brand-aws": TbBrandAws,
	"brand-azure": TbBrandAzure,
	"brand-google": TbBrandGoogle,
	"brand-vercel": TbBrandVercel,
	"brand-cloudflare": TbBrandCloudflare,
	"brand-firebase": TbBrandFirebase,
	"brand-supabase": TbBrandSupabase,
	"brand-stripe": TbBrandStripe,
	"brand-slack": TbBrandSlack,
	"brand-discord": TbBrandDiscord,
	"brand-telegram": TbBrandTelegram,
	"brand-whatsapp": TbBrandWhatsapp,
	"brand-x": TbBrandX,
	"brand-facebook": TbBrandFacebook,
	"brand-instagram": TbBrandInstagram,
	"brand-linkedin": TbBrandLinkedin,
	"brand-youtube": TbBrandYoutube,
	"brand-gmail": TbBrandGmail,
	"brand-openai": TbBrandOpenai,
	"brand-python": TbBrandPython,
	"brand-javascript": TbBrandJavascript,
	"brand-typescript": TbBrandTypescript,
	"brand-react": TbBrandReact,
	"brand-nextjs": TbBrandNextjs,
	"brand-vue": TbBrandVue,
	"brand-nodejs": TbBrandNodejs,
	"brand-golang": TbBrandGolang,
	"brand-rust": TbBrandRust,
	"brand-php": TbBrandPhp,
	"brand-laravel": TbBrandLaravel,
	"brand-django": TbBrandDjango,
	"brand-mysql": TbBrandMysql,
	"brand-mongodb": TbBrandMongodb,
	"brand-figma": TbBrandFigma,
	"brand-notion": TbBrandNotion,
	"brand-jira": TbBrandJira,
	"brand-trello": TbBrandTrello,
	"brand-paypal": TbBrandPaypal,
	"brand-apple": TbBrandApple,
	"brand-windows": TbBrandWindows,
	"brand-ubuntu": TbBrandUbuntu,
	"brand-debian": TbBrandDebian,
	"cloud": TbCloud,
	"cloud-upload": TbCloudUpload,
	"cloud-download": TbCloudDownload,
	"cloud-computing": TbCloudComputing,
	"cloud-lock": TbCloudLock,
	"cloud-data-connection": TbCloudDataConnection,
	"server": TbServer,
	"server-2": TbServer2,
	"server-bolt": TbServerBolt,
	"server-cog": TbServerCog,
	"database": TbDatabase,
	"database-export": TbDatabaseExport,
	"database-import": TbDatabaseImport,
	"database-search": TbDatabaseSearch,
	"database-plus": TbDatabasePlus,
	"database-cog": TbDatabaseCog,
	"table": TbTable,
	"table-export": TbTableExport,
	"topology-star": TbTopologyStar,
	"network": TbNetwork,
	"router": TbRouter,
	"wifi": TbWifi,
	"world": TbWorld,
	"world-www": TbWorldWww,
	"globe": TbGlobe,
	"link": TbLink,
	"unlink": TbUnlink,
	"lock": TbLock,
	"lock-open": TbLockOpen,
	"key": TbKey,
	"shield": TbShield,
	"shield-lock": TbShieldLock,
	"shield-check": TbShieldCheck,
	"fingerprint": TbFingerprint,
	"certificate": TbCertificate,
	"user": TbUser,
	"users": TbUsers,
	"user-plus": TbUserPlus,
	"user-check": TbUserCheck,
	"user-shield": TbUserShield,
	"id": TbId,
	"login": TbLogin,
	"logout": TbLogout,
	"mail": TbMail,
	"mail-forward": TbMailForward,
	"message": TbMessage,
	"messages": TbMessages,
	"bell": TbBell,
	"bell-ringing": TbBellRinging,
	"send": TbSend,
	"inbox": TbInbox,
	"calendar": TbCalendar,
	"calendar-event": TbCalendarEvent,
	"clock": TbClock,
	"clock-hour-4": TbClockHour4,
	"history": TbHistory,
	"hourglass": TbHourglass,
	"refresh": TbRefresh,
	"repeat": TbRepeat,
	"player-play": TbPlayerPlay,
	"player-pause": TbPlayerPause,
	"player-stop": TbPlayerStop,
	"rocket": TbRocket,
	"bolt": TbBolt,
	"flame": TbFlame,
	"sparkles": TbSparkles,
	"robot": TbRobot,
	"brain": TbBrain,
	"cpu": TbCpu,
	"cpu-2": TbCpu2,
	"device-desktop": TbDeviceDesktop,
	"device-mobile": TbDeviceMobile,
	"device-laptop": TbDeviceLaptop,
	"device-tablet": TbDeviceTablet,
	"device-watch": TbDeviceWatch,
	"printer": TbPrinter,
	"camera": TbCamera,
	"video": TbVideo,
	"microphone": TbMicrophone,
	"headphones": TbHeadphones,
	"volume": TbVolume,
	"photo": TbPhoto,
	"file": TbFile,
	"file-text": TbFileText,
	"file-import": TbFileImport,
	"file-export": TbFileExport,
	"file-zip": TbFileZip,
	"files": TbFiles,
	"folder": TbFolder,
	"folder-open": TbFolderOpen,
	"folder-plus": TbFolderPlus,
	"clipboard": TbClipboard,
	"clipboard-check": TbClipboardCheck,
	"notebook": TbNotebook,
	"book": TbBook,
	"bookmark": TbBookmark,
	"tag": TbTag,
	"tags": TbTags,
	"chart-bar": TbChartBar,
	"chart-line": TbChartLine,
	"chart-pie": TbChartPie,
	"chart-dots": TbChartDots,
	"report-analytics": TbReportAnalytics,
	"activity": TbActivity,
	"gauge": TbGauge,
	"target-arrow": TbTargetArrow,
	"trending-up": TbTrendingUp,
	"currency-dollar": TbCurrencyDollar,
	"credit-card": TbCreditCard,
	"shopping-cart": TbShoppingCart,
	"building-store": TbBuildingStore,
	"truck-delivery": TbTruckDelivery,
	"package-export": TbPackageExport,
	"box": TbBox,
	"box-multiple": TbBoxMultiple,
	"stack-2": TbStack2,
	"layers-intersect": TbLayersIntersect,
	"sitemap": TbSitemap,
	"hierarchy": TbHierarchy,
	"binary-tree": TbBinaryTree,
	"git-compare": TbGitCompare,
	"filter": TbFilter,
	"search": TbSearch,
	"adjustments": TbAdjustments,
	"settings": TbSettings,
	"tool": TbTool,
	"tools": TbTools,
	"wand": TbWand,
	"puzzle": TbPuzzle,
	"plug": TbPlug,
	"plug-connected": TbPlugConnected,
	"battery": TbBattery,
	"trash": TbTrash,
	"archive": TbArchive,
	"copy": TbCopy,
	"edit": TbEdit,
	"check": TbCheck,
	"x": TbX,
	"alert-triangle": TbAlertTriangle,
	"info-circle": TbInfoCircle,
	"help": TbHelp,
	"eye": TbEye,
	"map-pin": TbMapPin,
	"map-2": TbMap2,
	"compass": TbCompass,
	"flag": TbFlag,
	"star": TbStar,
	"heart": TbHeart,
	"thumb-up": TbThumbUp,
	"mood-smile": TbMoodSmile,
	"language": TbLanguage,
	"qrcode": TbQrcode,
	"barcode": TbBarcode,
	"scan": TbScan,
	"temperature": TbTemperature,
	"droplet": TbDroplet,
	"leaf": TbLeaf,
	"building-skyscraper": TbBuildingSkyscraper,
	"briefcase": TbBriefcase,
	"school": TbSchool,
	"microscope": TbMicroscope,
	"flask": TbFlask,
	"atom": TbAtom,
	"ticket": TbTicket,
	"gift": TbGift,
	"paperclip": TbPaperclip,
	"pin": TbPin,
	"lifebuoy": TbLifebuoy,
	"speakerphone": TbSpeakerphone,
	"broadcast": TbBroadcast,
	"antenna": TbAntenna,
	"satellite": TbSatellite,
	"keyboard": TbKeyboard,
	"mouse": TbMouse,
	"usb": TbUsb,
	"bluetooth": TbBluetooth,
	"share": TbShare,
	"download": TbDownload,
	"upload": TbUpload,
	"cloud-off": TbCloudOff,
	"loader": TbLoader,
	"chart": TbChartBar,
	"image": TbPhoto,
};

export const PREMADE_ICON_NAMES = Object.keys(PREMADE_ICONS) as PremadeIconType[];

export function premadeIcon(name: string | null | undefined): IconType | undefined {
	return name ? PREMADE_ICONS[name as PremadeIconType] : undefined;
}
